spring:
  thymeleaf:
    cache: false

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckill?userUnicode=true&characterEncodingUTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    hikari:
      pool-name: DateHikariCP
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 180000
      auto-commit: true
      max-lifetime: 180000
      connection-timeout: 30000
      connection-test-query: SELECT 1

  redis:
    #超时时间
    timeout: 10000ms
    #服务器地址
    host: 192.168.10.100
    #服务器端口
    port: 6379
    #数据库
    database: 0
    #密码
    password: root
    lettuce:
      pool:
        #最大连接数，默认8
        max-active: 1024
        #最大连接阻塞等待时间，默认-1
        max-wait: 10000ms
          #最大空闲连接
        max-idle: 200
          #最小空闲连接
        min-idle: 5






mybatis-plus:
  mapper-locations: classpath*/mapper/*Mapper.xml
  type-aliases-package: com.xxxx.seckill.pojo


logging:
  level:
    com.xxxx.seckill.mapper: debug

